### ISSUE TITLE
Support for EXT-X-I-FRAME-STREAM-INF or EXT-X-IMAGE-STREAM-INF

### ISSUE THREAD

**Issue by davidboutet** [videojs/http-streaming#1011]
Hello, it is not an issue but a question

Does EXT-X-I-FRAME-STREAM-INF or EXT-X-IMAGE-STREAM-INF is planned to be supported from an HLS manifest(.m3u8)

Or maybe an alternative to support trickplay directly from manifest.

Thanks

**Comment by gkatsev** [comment]
We don't support trickplay and I'm not aware of any MSE based player that does support it.
It's something that we're interested in but implementing it is likely _tricky_ and the benefit for it quite low compared to other areas we can spend our time on (like low latency live playback). It's unlikely that we'll get to it any time soon.

**Comment by bayaroch** [comment]
i have similar related question. how to keep every buffered segment files to seek back to where it starts.? also is there any resource explain about I-frame only playlist? My goal is i want to seek back 1 hour ago in live stream if i started watching 1 hour ago. Now i have only livewindow duration wich is max 300secs

**Comment by gkatsev** [comment]
There is no way to keep an hours worth of content buffered in the player client-side. The source buffers in MSE are quite small so they must get cleared frequently.

the i-frame playlists are basically what it says on the tin. The segments only include iframes which theoretically allow you to do faster seeks and during scrubbing you can show these quickly (since it's just an iframe and doesn't include the rest of the segment data). I'm not aware of any good resources on this as it's basically only used by iOS/Safari.

**Comment by z4yed** [comment]
Any update on this?
