### ISSUE TITLE
Video segements timing info use PTS or DTS time?

### ISSUE THREAD

**Issue by k8188219** [videojs/http-streaming#1080]
## Description
I'm using video.js@7.10.2 on an Android device running older WebView version(70.0.3538.110).
Playing test stream https://bitdash-a.akamaihd.net/content/sintel/hls/video/250kbit.m3u8 will cause error output in console.
`VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) video append of 3548b failed for segment #0 in playlist 0-https://bitdash-a.akamaihd.net/content/sintel/hls/video/250kbit.m3u8`

After investigation, I found out it's related to `sourceBuffer.timestampOffset`. If I force `timestampOffset = 0` then there's no problem (no error) appending segements to `sourceBuffer`, but the video won't start playing. 
Since `timestampOffset` is set base on `segmentInfo.timingInfo.start` and it's value comes from `probeTsSegment`, I finally found the source of this problem.
https://github.com/videojs/http-streaming/blob/327a57238dc034ebc1eee72bcfde1d8cfb2c5cf8/src/util/segment.js#L17-L38
If I change `ptsTime` to `dtsTime` video plays normally. (no need to force `timestampOffset = 0`)
I have little knowledge about this, but it seems that `dtsTime` is the wanted offset value.
Can someone correct me if I'm wrong?

## Sources
https://bitdash-a.akamaihd.net/content/sintel/hls/video/250kbit.m3u8

## Steps to reproduce
Use some older Android device to play HLS.

### Expected
The video plays normally.

### Error output
`VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) video append of 3548b failed for segment #0 in playlist 0-https://bitdash-a.akamaihd.net/content/sintel/hls/video/250kbit.m3u8`

### videojs-http-streaming version
videojs-http-streaming 2.2.4

### videojs version
video.js 7.10.2

### Browsers
Android WebView version 70.0.3538.110

### Platforms
Android 7.1.2

**Comment by pmendozav** [comment]
I have the same problem. I need to use `pause`  and `play` to start playback but it starts in time=X (where X is the segment size)

I observed that the segments are downloaded fine in order but seekable range is [X, ...>. That is, the first segment is missed

Using DTS instead of PTS works fine.. Also, I observed that in the past http-streaming used DTS instead of PTS

Finally, the latest release a new trigger was added in playback-watcher that allow to recover playback but this is not a fix because, the video starts in t=X like before and this starts after 9 o 10 segments are downloaded (maybe buffer filled)

**Comment by k8188219** [comment]
# update
This issue seems to related to chromium bug not allowing dts < 0.
https://bugs.chromium.org/p/chromium/issues/detail?id=398141

I can get this to work is because the first frame is an I-frame thus it's PTS is larger than DTS
