### ISSUE TITLE
process segments with decodeAudioData

### ISSUE THREAD

**Issue by thijstriemstra** [videojs/http-streaming#1103]
## Description
I would like to render a waveform for each segment. When I edit the `xhr` function like this:

```js
tech.vhs.xhr.beforeRequest = function (options) {
    console.log(options);
    return options;
};
```

I can see the various arraybuffers that are loaded:

```
{
  "timeout": 16500,
  "withCredentials": false,
  "handleManifestRedirects": true,
  "uri": "https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/gear2/main.ts",
  "responseType": "arraybuffer",
  "headers": {
    "Range": "bytes=678116-1346455"
  }
}
```
but so far I'm unable to access the arraybuffer that I'd like to pass to `AudioContext.decodeAudioData`. Any idea if this is possible?

### videojs-http-streaming version
videojs-http-streaming that comes with video.js 7.10.2

### videojs version

video.js 7.10.2

### Browsers
Chrome, Firefox

### Platforms
Ubuntu

**Comment by gkatsev** [comment]
`beforeRequest` won't help you there as it just allows you to update the options. Your best bet right now is to override the `xhr` method altogether. While it's not something we often recommend, sometimes it's the only way. We recently made it so that you can actually [override it early](https://github.com/videojs/http-streaming/pull/1059) to get access to requests as early as the main manifest (which previously you'd miss). You can set it via `videojs.Vhs.xhr`.
At some point, we plan to provide a way to hook into these to get the requests without needing to override the xhr method, but unfortunately, right now that's more or less the only way.

**Comment by thijstriemstra** [comment]
thanks for the feedback @gkatsev 

`videojs.Vhs.xhr.beforeRequest` looks like it's functioning the same as `tech.vhs.xhr.beforeRequest`.

I'm trying to understand the structure of the object video.js/http-streaming passes to `beforeRequest`, e.g:

`
{
  timeout: 16500,
  withCredentials: false,
  handleManifestRedirects: true,
  uri: "https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/gear1/main.ts",
  responseType: "arraybuffer",
  headers: {Range: "bytes=0-326743"}
}
​`

The `responseType` is arraybuffer, which is what I need to pass to `decodeAudioData`. Instead of loading that `main.ts` URI again (which won't work since it's a mimetype the browser doesn't understand: `video/MP2T`), I would expect the `arraybuffer` belonging to that URI to be available somewhere in an internal var inside http-streaming, that I can simply pass to `decodeAudioData`. Any idea?

**Comment by gkatsev** [comment]
The object is basically https://github.com/naugtur/xhr#var-req--xhroptions-callback
Unfortunately, the response data isn't available anywhere that you can access from outside VHS internals, even via private properties.
