### ISSUE TITLE
auto quality is switching renditions even with good internet quality 

### ISSUE THREAD

**Issue by KVPasupuleti** [videojs/http-streaming#1112]
## Description
When the auto option is selected, it would enable all the renditions and `vhs` would take care of switching between them.
Hence, if there is a decent internet connection, in auto mode, the video must be played with the highest quality we have in the quality levels list. But, as a surprise, the video is switching between the renditions with different qualities like 240, 360, 480, and 720. Whereas, if we select the highest quality we have, the video is playing without any buffering.

On what basis does `vhs` switch between the renditions in auto mode? Is this behavior expected?

## Sources
We are using `dash` and `hls` type sources. This is happening with both type of sources

## Steps to reproduce

1. Give a dash type source to the video player 
2. Select auto option from the quality levels
3. Observe the network tab for the sources that are being fetched

### Expected
The video should play at a consistent quality level when we have a decent internet connection

### Actual
The quality levels are getting switched frequently even with a decent internet connection

### Error output
No errors

### videojs-http-streaming version
videojs-http-streaming 1.12.0

### videojs version
video.js 7.6.6

### Browsers
Chrome 89

### Platforms
Linux

### Other Plugins
videojs-contrib-dash 2.11.0
videojs-contrib-quality-levels 2.0.9
videojs-http-source-selector 1.1.6

### Other JavaScript
React ^16.12.0
mobx 5.15.0

**Comment by ziddey** [comment]
Have you tried setting `videojs.log.level('debug')`? Might log the reason behind the switch

Or maybe try the new experimental buffer based abr by setting `options.html5.vhs.experimentalBufferBasedABR` to `true`: https://github.com/videojs/http-streaming/pull/886

**Comment by gkatsev** [comment]
Thanks @ziddey. Yeah, I would recommend setting `experimentalBufferBasedABR`. Our current default ABR is a bit naive and only takes into account the previous segment download, which means that as internet usage fluctuates (which it does even with "good" internet) we may end up switching down or up too much. A lot of it is fixed with `experimentalBufferBasedABR` and we do plan on enabling it by default soon.

**Comment by Kaywee27** [comment]
Thanks, @ziddey and @gkatsev. `experimentalBufferBasedABR` is working great. And it's working 80-85% of the time.

But, I got an issue here.

For a use case, we are trying to play a recorded video as `live` using timers and handling the seek bar position using `player.currentTime`. We are using `StreamingNow` button too so that the user can go to the right most in live.

We are using `v1.12.0`.

As `experimentalBufferBasedABR` is supported well in higher versions, I upgraded the package to `v2.8.0`

Everything seems working, but I couldn't get this live feature working.

- Sometimes, I couldn't handle the seek bar position
- Sometimes, I couldn't see the StreamingNow button

But, with `v1.12.0`, the live feature is working without any issue.

Is there any reason behind all these I am not able to understand?

**Comment by gkatsev** [comment]
Sounds like a separate issue. There's been *a lot* that's changed between 1.12 and 2.8, so, it would be incredibly hard to narrow things down. If you can open a new issue with an example of what you're doing and what you're expecting and what's happening instead, we can take a look. We would expect seeking to work, generally, though.
I would also definitely not recommend using v1 anymore, though, if it's working for you, I guess it's fine.

**Comment by gkatsev** [comment]
Is this something that we can close? It sounds like it's fixed by `experimentalBufferBasedABR`.

**Comment by KVPasupuleti** [comment]
Yes. We can close this.
