### ISSUE TITLE
How to check if HLS is in use

### ISSUE THREAD

**Issue by gyanex** [videojs/http-streaming#1139]
How to check if HLS is in use before using
var vhs = player.tech().vhs;

**Comment by gkatsev** [comment]
Do you want to know if VHS is being used for playback? Or that HLS is being played? For checking VHS, if `player.tech().vhs` is an object, it means VHS is used. For checking that HLS is used, you can check `player.currentType()` and see whether it's one of the HLS mime types, this is useful because HLS on Safari uses native playback by default.
