### ISSUE TITLE
MEDIA_ERR_SRC_NOT_SUPPORTED is getting thrown and is gone when reloaded

### ISSUE THREAD

**Issue by KVPasupuleti** [videojs/http-streaming#1177]
## Description
In our application, we are showing the users a banner asking them to upgrade their device when this error is reported(By listening to `player.on('error')` and checking if the `player.error().code === 4`). But, sometimes we are observing this behavior.

This error is getting reported even when the device and browser support the source and when the user reloads the page, the video is playing without issue.

Is there any other case in which this error is thrown by the player? 
Is this something that happens often? 
And is there something that can be done to fix this? 

## Sources
I couldn't provide a proper source because this is not something that's exactly reproducible every time. It's like a random behavior on all of our sources(.mpd and .m3u8 sources).

### Expected
The error should be thrown only when the source is not supported by the browser. And its behavior should be constant across a device or a  browser.

### Error output
The error is thrown sometimes even when the browser and the device support the source. And, it's not getting thrown when the page is reloaded. 

### videojs-http-streaming version
videojs-http-streaming 2.9.1 included with videojs inbuilt

### videojs version
video.js 7.13.3

### Browsers
Chrome 91

### Platforms
Windows 10, Ubuntu 18.04

### Other Plugins
videojs-http-source-selector 1.1.6
videojs-contrib-quality-levels 2.1.0

### Other JavaScript
Mobx 5.15.0

**Comment by gkatsev** [comment]
That error happens when the browser (or us via the browser) are trying to play a video encoded in a codec that isn't supported.
My initial guess as to why it happens sometimes is that it's potentially a timing issue. Though, it's hard to know with a sample page showing the implementation. 
One of the things that Video.js does is if the browser has started loading the video already, it will let it handle loading. However, most browsers can't play HLS or DASH natively, so, if they start loading things, they will break.
So, for example, if you're using a `<video>` element embed
```html
<video controls class="video-js" data-setup="{}">
  <source src="https://example.com/video.m3u8" type="application/x-mpegurl">
</video>
```
If Video.js happens to run too slowly, the browser will try to load things and then fail with MEDIA_ERR_SRC_NOT_SUPPORTED. A potential fix is to use `<video-js>` element or load the source manually after the fact.

**Comment by KVPasupuleti** [comment]
COOL

I have changed the `<video>` element to `<video-js>` in our React :heavy_plus_sign:  Styled-components way of implementation. 

Will deploy this version and get back if there is any unexpected behavior.  

Thanks for the info. 

I could see its reference in the docs [here](https://docs.videojs.com/tutorial-setup.html).
If this is the case, we could recommend this by default in the docs. Is there any reason for not doing that?

**Comment by gkatsev** [comment]
Glad it works for you. The issue with docs is that we have a lot of docs that while valid isn't using the latest and greatest things as you mentioned. However, the old things generally still works.
Also, we mention `<video-js>` in this other doc https://docs.videojs.com/tutorial-embeds.html
