### ISSUE TITLE
Audio and Video are not in sync

### ISSUE THREAD

**Issue by KVPasupuleti** [videojs/http-streaming#1178]
## Description
While playing the video in a low resolution like 360p or 240p with a slow network (this actually happens with all resolutions, but to be playable with low network speeds, I have quoted these resolutions),  audio and video are not in sync. The video is getting stuck and the audio is played. 

I believe this is probably a timing issue where the audio chunks are requested prior to respective video chunks. Hence, the audio is getting played when the video chunk is still in a fetching state.   

It's also happening more often when the browser is caching the audio chunks and not caching video chunks properly. 

Please check [this](https://codesandbox.io/s/testing-vanilla-video-js-nms5s?file=/index.html:950-1028) sandbox link to reproduce the issue.

or

Go to the videoJS [demo](https://videojs-http-streaming.netlify.app/) to reproduce the issue

## Sources
https://dash.akamaized.net/dash264/TestCasesHD/2b/qualcomm/1/MultiResMPEG2.mpd

This is an example source I have taken from [this](https://ottverse.com/free-mpeg-dash-mpd-manifest-example-test-urls/) website.

But, it's happening with almost all the sources listed in the videoJS demo too as far as I tested.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Go to any of the provided demo links
2. Change network speed to slow 3G from Chrome Dev tools
3. Seek the video to a duration where the chunks are not loaded yet
4. Observe the sync between audio and video

### Expected
Audio and Video should be played in sync. If the network is slow, the audio chunks should not go ahead of the video chunks. 

### Actual
Audio is playing ahead of the Video when the video chunk is still in a fetching state.

### videojs-http-streaming version
videojs-http-streaming 2.9.1 included with videoJS inbuilt

### videojs version
video.js 7.13.3 and if the videoJS demo is the latest, it's in the latest version too

### Browsers
Chrome 91

### Platforms
Ubuntu 18.04

### Other Plugins
videojs-http-source-selector 1.1.6
videojs-contrib-quality-levels 2.1.0

**Comment by KVPasupuleti** [comment]
@gkatsev @mister-ben could you please go through this issue?

**Comment by gesinger** [comment]
Hey @KVPasupuleti , this looks like a case of video underflow, and is expected behavior. If the video can't be buffered fast enough, most playback engines will continue to play audio for a certain duration of time while it hopes to catch up the video buffer. This is because interrupted audio playback can be jarring, whereas video interruptions are less jarring. It will happen more frequently with lower bandwidth, as the video can't be buffered fast enough to prevent the issue from occurring (and audio generally requires less bandwidth). For a more in-depth description and example of the behavior, we have a comment around some code that identifies gaps from video underflow here: https://github.com/videojs/http-streaming/blob/a11f258367769d943d0e7fdec91a8de14edae83a/src/playback-watcher.js#L602-L623

Hope this helps!
