### ISSUE TITLE
ext-x-discontinuity causes endless buffer in chrome. Working fine in FireFox.

### ISSUE THREAD

**Issue by asadmalik3** [videojs/http-streaming#1209]
## Description
My stream containing ext-x-discontinuity tag is buffering endlessly on chrome although the same stream is working fine on Firefox. Please note that other m3u8 not having ext-x-discontinuity tag are working fine in chrome.

## Sources
I cannot provide the stream URL, but I am pasting down the content of the m3u8 file below.

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:8746
#EXT-X-DISCONTINUITY-SEQUENCE:8742
#EXT-X-DISCONTINUITY
#EXTINF:10.0,
media_w1092822639_b920880_8746.ts
#EXT-X-DISCONTINUITY
#EXTINF:10.0,
media_w1092822639_b920880_8747.ts
#EXT-X-DISCONTINUITY
#EXTINF:10.0,
media_w1092822639_b920880_8748.ts
```

## Steps to reproduce
N/A

## Results
It should work seamlessly in chrome too.

### Error output
No

### videojs version
7.8.4

### Browsers
Google Chrome 93.0.4577.82

### Platforms
Windows 10

**Comment by gkatsev** [comment]
Do you have a main manifest with different renditions, or is this the only playlist?
Also, can you try with the latest version of Video.js? Or on https://videojs-http-streaming.netlify.app/?

In addition, while you can definitely have a discontinuity on every segment, it isn't recommended because it means the decoder needs to be reset for every segment.

What do you mean by "buffering endlessly"? Is it downloading more and more segments, or just sitting there waiting?

**Comment by gkatsev** [comment]
Ultimately, this isn't something we can help out without a sample stream.

**Comment by asadmalik3** [comment]
**Do you have a main manifest with different renditions, or is this the only playlist?**
@gkatsev This is a live stream playlist with only 1 quality (720 P).

**Also, can you try with the latest version of Video.js? Or on https://videojs-http-streaming.netlify.app/?**
It works better with latest version but still waiting state is a bit too much. Earlier, I was using video js 7.8.4, and playback experience was quite poor. Player goes into waiting state after discontinuity tag and never recover from there.


**What do you mean by "buffering endlessly"? Is it downloading more and more segments, or just sitting there waiting?**
I mean player goes into buffering state after every chunk. Player throws waiting event and then start playing video after some time.

**In addition, while you can definitely have a discontinuity on every segment, it isn't recommended because it means the decoder needs to be reset for every segment.**
I understand that having discontinuity tag after every segment pushes player into reset/buffering mode. Interesting fact is that video playback is smooth in Firefox, player never goes in waiting mode in Firefox. Seems like this tag is being ignored in Firefox. Additionally this is working fine in Safari too.

Is there a way other than sample stream to get your help on this?

**Comment by gkatsev** [comment]
I don't think that the other browsers are ignoring these the discontinuities, but they probably just handle things differently than Chrome. We've seen streams that fail in one browser but don't have issue with others due to differences in how the browsers handle edge cases.
We can definitely try a local stream with a bunch of discontinuities, but it may not showcase the same issue that you're seeing. For these types of issues, we often can't really help without a sample because there's too many potential issues of what could be producing the issue and if we can't reproduce it is isn't really something that we can work on a fix or come up with a workaround for.
