### ISSUE TITLE
Audio Sync with multiple audio tracks

### ISSUE THREAD

**Issue by Smith-Chris1** [videojs/http-streaming#154]
## Description
I'm seeing audio out of sync with live streams and multiple audio tracks. This is not consistent, a refresh might fix it or it might not. This appears to only happen in videojs players.

## Sources
https://83179832e18c442282473f1dc588a588.dlvr1.net/out/u/0626deltaDVR/master4.m3u8

## Steps to reproduce

1. Load the source in a videojs player
2. Hit play - if its in sync, refresh and try again - it will eventually be out of sync.

### Expected
I expected the audio to be in sync.

## Additional Information
Here is a Brightcove player (built on videojs) with the same problem. 
https://players.brightcove.net/710857117001/default_default/index.html?videoId=5808118098001

### videojs-contrib-hls version
All - I've tried multiple versions.

### videojs version
All - I've tried multiple versions

### Browsers
All browsers

### Platforms
All

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
*

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
*

**Comment by squarebracket** [comment]
I'm quite certain this is the same issue that I tried to solve with videojs/videojs-contrib-hls#1379.

The underlying problem is that we offset the DTS values for live feeds to start at 0s. If the segments are of exactly the same duration, then this isn't a problem since the DTS values at the start of each segment should match between the video and the audio. But in any wonky system like NTSC you'll usually get segments of differing length and so you end up having to sync the difference in DTS between the two.

My PR seemed to flip the incident rate -- most of the time it would be in sync, but every now and then it wouldn't be or would fail to start. There's obviously a more complicated interaction with the sync controller, which I couldn't figure out. Perhaps someone more senior in the playback team has some insight.

**Comment by Smith-Chris1** [comment]
I have changed my settings on my encoder to the following:

FPS - 29.97 drop
GOP - 90
Segment Length - 6 seconds

This seems to have fixed the sync issue. We'll keep testing.
