### ISSUE TITLE
 Add redirect support for manifest and media requests (from contrib-hls)

### ISSUE THREAD

**Issue by forbesjo** [videojs/http-streaming#290]
Bring over https://github.com/videojs/videojs-contrib-hls/pull/1213

**Comment by forbesjo** [comment]
This is already in contrib-hls, there needs to be a new PR to sync up this feature

**Comment by gkatsev** [comment]
This is being worked on.

**Comment by Stijn98s** [comment]
I have currently the problem that safari and edge dont work because they use the redirected url. example www.example1.com/video.m3u8 redirects to www.example2.com/video.m3u8. in the video.m3u8 are redirects to different videos (video_1080p.m3u8, video_720p.m3u8 etc). All the calls to the video_1080.m3u8 fail on safari and edge because they use the www.example2.com base where they are not available (because the redirected url is a private s3 bucket and need a presigned url from www.example1.com). chrome still uses the www.example1.com url. Is there a way to fix this?

**Comment by gkatsev** [comment]
`handleManifestRedirects` is in VHS and off by default right now.

I think we discussed the previous comment's issue on slack, but what they're doing is a bit unexpected but also there's little that can be done in VHS since on Safari native playback is being used. The ideal fix for this scenario is to use fully qualified urls rather than relative urls.
