### ISSUE TITLE
HLS stream only plays audio

### ISSUE THREAD

**Issue by clintonbosch** [videojs/http-streaming#434]
__Please do not delete the template, by filling out the required information we can investigate your issue more quickly.__

## Description
There is a particular hls manifest that only plays the audio track and not the video on videojs. Other js players seem to be able to play the video, but not videojs

## Sources
https://kmtv-appeartv-stream.imigino.com/3/0/hls/KMTV/playlist.m3u8

## Steps to reproduce
Simply open the test page https://videojs.github.io/http-streaming/ and input the abovementioned stream URL

## Results
Only the audio track plays and no video

### Expected
Expected video to play as with any of the following players:
http://demo.jwplayer.com/developer-tools/http-stream-tester/
http://bitmovin.com/demos/stream-test
http://player.kaltura.com/modules/KalturaSupport/tests/HLSPlaybackTester.html

### Error output
No errors visible in the console

## Additional Information
It does also not seem to play using the old contrib-hls library either so any advice why this stream is not compatible would be much appreciated

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 1.9.1

### videojs version
what version of videojs does this occur with?
video.js 7.4.1

### Browsers
Have not been able to get this stream to play on any desktop browsers tested so far

### Platforms
Tested on windows and linux

### Other Plugins
None

### Other JavaScript
None

**Comment by squarebracket** [comment]
This is likely caused by having only an audio-only playlist and a high-bandwidth audio+video playlist. The short version of the problem is that the initial bandwidth calculation thinks it isn't sufficient for selecting the audio+video playlist, so it picks the only-audio one, which unfortunately locks it to being audio-only forever, preventing a switch to the audio+video playlist when it gets a better estimation of bandwidth.

We have [an open issue](https://github.com/videojs/http-streaming/issues/175) for only allowing audio+video playlists when there are both audio-only and audio+video playlists in the manifest, but unfortunately, we haven't been able to implement that behavior yet. In the mean time, doing either of these will let you get around this:
- set the [`enableLowInitialPlaylist` option](https://github.com/videojs/http-streaming#enablelowinitialplaylist) -- this is the best option, since it should always select the lowest-bandwidth audio+video playlist for its first playlist
- set the [`bandwidth` option](https://github.com/videojs/http-streaming#bandwidth) to a value high enough to select the audio+video playlist -- for this media, the effect should be the same as using `enableLowInitialPlaylist` since there's only one audio+video playlist, but it's something you may want to keep in mind if you add more rates

It's also worth mentioning that Apple no longer recommends having an audio-only rate; instead, they recommend a very-low-bitrate audio+video rate. Removing the audio-only rate would of course eliminate this problem since there would be only audio+video playlists to choose from.
