### ISSUE TITLE
ffmpeg examples

### ISSUE THREAD

**Issue by bootrino** [videojs/http-streaming#619]
It would be **much** easier to implement this technology with examples of how to create compatible video streams for ffmpeg.

I've searched etensively and whilst I think maybe there might be relevant examples out there I just don't know.

So I'd like to get straight on with the job of implementing  videojs http-streaming into my application but I really have no idea how to create compatible video streams.

**Comment by bloomtom** [comment]
What's your use case for http-streaming? Live/VOD, HLS/DASH? Examples for live streaming are available on the [ffmpeg wiki](https://trac.ffmpeg.org/wiki/StreamingGuide). Video on demand is where things usually get a little stickier, since the source files can be a mess, and the presence of multiple channels of audio/subtitles makes things more difficult. This is where I've been working (VOD DASH) for a while, and I can't say there's been one good source for everything.
