### ISSUE TITLE
DASH live constantly requests a Manifest file from the server

### ISSUE THREAD

**Issue by zhulduz** [videojs/http-streaming#658]
## Description
I noticed that after I stop a player, even if I dispose of it, the video player continue request manifest file. It appears only for MPEG-dash type.

This issue appears also in the example player.

## Steps to reproduce

1. Open example player https://videojs.github.io/http-streaming, set any dash live stream, for example `https://livesim.dashif.org/livesim/mup_30/testpic_2s/Manifest.mpd` and play video
2. Open network tab
3. Stop the player

## Results
The player will continue request manifest file

### Expected
But shouldn't

### videojs-http-streaming version
the latest

### videojs version
the latest

### Browsers
any
*

### Other Plugins: videojs-dash-contrib or bitmovin
https://videojs.github.io/videojs-contrib-dash/

What should I do with a such problem? Is there known similar issues?

Thanks in advance

**Comment by zhulduz** [comment]
Any suggestions?
Why videojs requests Dash manifest file even the player is removed from DOM?

**Comment by mjneil** [comment]
Pausing the player, it is expected the dash manifest would continue to be requested because of the `minimumUpdatePeriod="PT30S"` attribute. However, the player should stop those requests after `player.dispose()`. I am unable to reproduce the issue when calling `player.dispose()`. The requests stop for me. Would you be able to put together a reduced example that has this issue?
