### ISSUE TITLE
hlsQualitySelector show/hide button manually

### ISSUE THREAD

**Issue by jonathanbrenman** [videojs/http-streaming#675]
Hi All,

How can I show/hide the VHS quality button (HD) programatically once the player was initializated in videoJS 7?

It's showing on Desktop but not in mobile so I would like to try setting up via JS.

Thank you

**Comment by gkatsev** [comment]
VHS doesn't ship with a quality selector button. An API is provided via https://github.com/videojs/videojs-contrib-quality-levels and it is possible that you're using some other plugin that interfaces with it.
However, working on desktop versus mobile likely means that native playback is being used instead of VHS. You'll want to set overrideNative: https://github.com/videojs/http-streaming#overridenative. Just note that iphones and ipads with ios 12 and older cannot use VHS.
