### ISSUE TITLE
HLS will only play up to 720p

### ISSUE THREAD

**Issue by mkariti2** [videojs/http-streaming#713]
## Description
Playing HLS files will load 720p at most using videojs. However, on other hls online player I'm able to get the 1080p and above.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. go to https://jsbin.com/gejugat/edit?html,output
2. insert the https://footage-hls.azureedge.net/footage-hls-slider/12453_playlist.m3u8 to any videojs player
3. I'm getting 720p only. (able to switch to a higher quality using quality selector)
 

## Results
On good internet connection will get only 720p
### Expected
Should get 1080p and above

### videojs-http-streaming version
  "@videojs/http-streaming": "1.10.6",

### videojs version
    "video.js": "~7.6.5",

### Other Plugins

    "videojs-contrib-quality-levels": "~2.0.9",
    "videojs-hls-quality-selector": "~1.0.5",

### Other JavaScript
Angular 8

**Comment by gkatsev** [comment]
Our bitrate switching algorithm limits the renditions based on the player dimensions to conserve bandwidth, see https://github.com/videojs/http-streaming/blob/master/docs/bitrate-switching.md.
You can disable this, you can set https://github.com/videojs/http-streaming#limitrenditionbyplayerdimensions.

**Comment by mkariti2** [comment]
@gkatsev, Many thanks for this quick answer. H5YR!

**Comment by mkariti2** [comment]
@gkatsev, unfortunately, this does not seem to work.  
Ive added the limitRenditionByPlayerDimensions under the hls section in the option with no success. 
Any idea on why this may not work?

**Comment by gkatsev** [comment]
I think it's because your test stream is so short. We choose our initial rendition to be closest to 0.5MB/s (https://github.com/videojs/http-streaming/blob/master/src/config.js#L5-L6). Locally, I can see that after it loads the 720p rendition and the two segments it will then download the 2160p manifest with the option. Without the option, because my player was small, it was actually then downloading the 480p rendition.
You can set the [`bandwidth` option](https://github.com/videojs/http-streaming#bandwidth) to start at a higher rendition if you want and if I set it to a really high value I can see it loading either 720p or the one matching the bandwidth value depending on whether I have `limitRenditionByPlayerDimensions` set.
Hope this helps.

**Comment by mkariti2** [comment]
work like a charm!
