### ISSUE TITLE
HLS never finishes when last fragment is too short

### ISSUE THREAD

**Issue by pmendozav** [videojs/http-streaming#725]
## Description

I'm working with HLS VOD manifests and found that when the last fragment is too short it is not taken account and video never finishes. 

For example, using this manifest:
```http://d2ufudlfb4rsg4.cloudfront.net/abc7/lrgD6Yh9f/adaptive/large/f.m3u8``` 
that has 22 fragments, ```EXT-X-TARGETDURATION=8``` and ```EXTINF=4.096``` for all the segments except the last which has ```EXTINF=0.032```

Waiting until all the fragments are downloaded and reach the video end. Looking at `videojs.tech_.hls.playlists.media_` I found this: Each segment has start, end, duration fields, where ```end = start + duration```. For this example, in the last segment (`uri=F00000022.ts`) I have `start=139.2639888888889`,  `duration=0.032` and `end=139.2639888888889`. Also, looking `videojs.tech_hls.stats` I have that `duration=139.2639888888889`, `buffered.end=139.239021` and `currentTime=139.253065`

That is, once all the video is buffered and `currentTime()=139.253065` looks like it wait to continue because duration is `139.2639888888889` but it can't because all the fragments are currently buffered.

The test case is the official web demo at https://videojs.github.io/http-streaming/

## Sources

Check `videojs.tech_.hls.playlists.media_` and `videojs.tech_hls.stats`

## Steps to reproduce

1. Go to https://videojs.github.io/http-streaming/
2. In `Video URL` use `http://d2ufudlfb4rsg4.cloudfront.net/abc7/lrgD6Yh9f/adaptive/large/f.m3u8`
3. In the inspector open videojs.js and put a breakpoint inside `timeupdateHandler` method (line 8901 for me).
4. Start playback and wait until the video end, it will keep in a loop and nothing happens. To be sure to force the breakpoint `pause` and `play`.
5. Check `videojs.tech_.hls.playlists.media_` and `videojs.tech_hls.stats` properties

### Expected
The video should be end but keep in a loop.

### Error output
No error reported

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
videojs 7.6.6
(videojs-http-streaming is included)

### videojs version
videojs 7.6.6
(videojs-http-streaming is included)

### Browsers
what browsers are affected? please include browser and version for each
* Google Chrome: Version 79.0.3945.130 (Official Build) (64-bit) 

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* MacOS Mojave: Version 10.14.6 (18G84)

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
* Tested in the official demo at https://videojs.github.io/http-streaming/ 

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
* No

**Comment by EhsanCh** [comment]
I have this issue on v1.11.2 with vjs 6.12.1

**Comment by k-harker** [comment]
I think I ran into a similar issue.  My use case is a little different than having a single frame at the end.  I'm trying to test having single frame segments after a discontinuity, possibly several single frame ts files.

I found that there is an issue with having ts files that contain only a single frame.  When working with two frame ts files I did not have any issues. Looking at mux.js it looks like it determines the length of a frame by looking at the dts of video frames in the segment.  When there is a single frame, it comes back with a 0 duration for the frame.  When this happens sometimes videojs hangs with the spinner for a time in Chrome.  Firefox either skips the frame or gets hung up on it as well.  

Looking at the method `groupNalsIntoFrames` in mux.js I was able to get around this by checking the length of the last frame before it gets pushed into the frames array.  When it doesn't have a duration I add one since I know the duration of the other frames in the video.  I'm thinking about just using the last processed frames duration instead of a hard coded value like it is here.  I'm sure there's problems with this approach so I'm hoping someone here understands this better and can propose a better fix.

```
frames.byteLength += currentFrame.byteLength;
frames.nalCount += currentFrame.length;

// this is the line I added to get it to work
if (!currentFrame.duration) currentFrame.duration = 3003;

frames.duration += currentFrame.duration;
frames.push(currentFrame);
return frames;
```

**Comment by gesinger** [comment]
Hey @pmendozav , took a look today and noticed that there was an error that wasn't percolated up the chain: "Only audio found in segment when we expected video. We can't switch to audio only from a stream that had video. To get rid of this message, please add codec information to the manifest." You can see it under: `player.vhs.masterPlaylistController_.mainSegmentLoader_.error()`

Looking at the last segment, there's only one frame, and it is an audio frame. Right now VHS isn't set up to handle muxed content with a segment where there's only a single track of media (audio only or video only when we started with muxed audio and video in a segment). Support for this may be added in the future, but we don't have a timeline for it.

We also should surface that error better. That may be a more immediate action we can take.

Try adding at least a video frame alongside the audio into the last segment. This should help resolve the error.

**Comment by third774** [comment]
I think this is still an issue

**Comment by gkatsev** [comment]
We believe that a short last segment is fixed in master. The issue from the original poster as outlined by @gesinger is something that we do not currently support.
