### ISSUE TITLE
How does videoJS determines quality of first segment?

### ISSUE THREAD

**Issue by csalmeida** [videojs/http-streaming#739]
## Description

I have been using videoJS using a stream in `.m3u8` segments. However, even with a fast internet connection the first segment will always be `360p` and will change later to `1080p` or another quality level at around 5/6 seconds into the video.

I am far from being an expert on how video streaming works so I was hoping one of the maintainers or someone more experienced could give me some tips on how to handle this.

I have used a few methods to bump the quality such as setting a minimum quality level:

```javascript
player.tech().hls.representations().forEach(function(rep) {
  if (rep.width >= 1920) {
    rep.enabled(true);
  } else {
    rep.enabled(false);
  }
});
```

This works, however it will still retrieve the first chunk at `360p` and then retrieve it again at `1080p`. There is also the issue that it is forcing it and therefore users with slower connections will have to wait until the `1080p` segment downloads before playing the video.

Then I've increased the bandwidth which allows the first segment to be higher quality form the get go! However, when the network is throttled to "Good 3G" it will still request `720p` and then the segment seems to be requested again at `360p`.

```javascript
var options = {
  autoSetup: false,
  preload: 'metadata',
  autoplay: false,
  loadingSpinner: true,
  html5: {
    hls: {
      limitRenditionByPlayerDimensions: false,
      bandwidth: 6194304
    }
  }
};

var player = videojs('my_video_1', options);
```

How does videoJS determines quality of first segment?

The clip I'm using is `~20s`, is there a way for videoJS to adjust quality starting from first segment in such a short video?

## Sources
I do not have any public segments available but please see screenshots below.

Using default settings for handling quality (first segment is always 360p):
<img width="1071" alt="Screenshot 2020-02-18 at 11 09 16" src="https://user-images.githubusercontent.com/12223613/74731248-8706ab80-523f-11ea-8048-9f745fd0cefb.png">

Bumping `bandwidth` will make the first segment `720p`:
<img width="1071" alt="Screenshot 2020-02-18 at 11 13 07" src="https://user-images.githubusercontent.com/12223613/74731437-dd73ea00-523f-11ea-88f2-b38021b1e154.png">

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Instantiate a videoJS player.
2. Set source to an HLS stream. 
3. Check network panel on devtools.

### Expected
How does videoJS determines quality of first segment?

The clip I'm using is `~20s`, is there a way for videoJS to adjust quality starting from first segment in such a short video?

### Error output
N/A

### videojs-http-streaming version
videojs-http-streaming (the one included in videoJS 7)

### videojs version
video.js `7.6.6`

### Browsers
* Firefox `72.0.2 (64-bit)`
* Chrome `Version 79.0.3945.130 (Official Build) (64-bit)`

### Platforms

* MacOS `10.15.2`

### Other Plugins

* N/A

### Other JavaScript

* N/A

**Comment by csalmeida** [comment]
Additionally, is this still applicable? https://github.com/videojs/videojs-contrib-hls/blob/master/docs/bitrate-switching.md

**Comment by gkatsev** [comment]
Yup, the bitrate switching doc is still applicable. See https://github.com/videojs/http-streaming/blob/master/docs/bitrate-switching.md for the current version, though, I don't think it's changed much.
We choose renditions based on the player size and also by default we aim to get something as close to 0.5MBps https://github.com/videojs/http-streaming/blob/e9c5a655ddf4d252d75b755f522726eea3436f28/src/config.js#L5-L6
You can use the [`bandwidth`](https://github.com/videojs/http-streaming#bandwidth) option to use a different starting point. The reason we do this is because otherwise, we have no other starting point of what to download.
As outlined in the doc above, we limit the rendition by the player size, you can turn that off by setting [`limitRenditionByPlayerDimensions`](https://github.com/videojs/http-streaming#limitrenditionbyplayerdimensions).

**Comment by csalmeida** [comment]
Really helpful, thanks for explaining this further! 🙇🏻‍♂️

**Comment by gkatsev** [comment]
You're welcome!

**Comment by simeyla** [comment]
One thing I've noticed (and this has literally confused me for years) is that `limitRenditionByPlayerDimensions` defaults to `true` but `useDevicePixelRatio` defaults to `false`.

So what happens (I stepped through the code) is that on mobile you may have a video 300px wide but on my iPhone that's actually 900px in reality. But video-js chooses the 360px width video so it starts terribly.

The fix for me was simple - just set `useDevicePixelRatio: true`
```
   hls: {   
      limitRenditionByPlayerDimensions: true,
      useDevicePixelRatio: true
   },
```

My videos are very short looping videos (3-10 seconds) so a fast start is way less important than crisp, consistent video. Especially on a fast connection when it's perfectly capable of downloading the good video.

@gkatsev I think the docs need to suggest under the `limitRenditionByPlayerDimensions` option that `useDevicePixelRatio` should probably be enabled at the same time. There are probably historical reasons why `useDevicePixelRatio` isn't used but I certainly don't ever want it disabled for what I'm doing.

----

For reference:

### limitRenditionByPlayerDimensions
When limitRenditionByPlayerDimensions is set to true, rendition selection logic will take into account the player size and rendition resolutions when making a decision. This setting is true by default.

### useDevicePixelRatio
If true, this will take the device pixel ratio into account when doing rendition switching. This means that if you have a player with the width of 540px in a high density display with a device pixel ratio of 2, a rendition of 1080p will be allowed. This setting is false by default.

**Comment by gkatsev** [comment]
`useDevicePixelRatio` was added at the height of the pandemic and was kept defaulted to off to minimize bandwidth usage. It's probably not unreasonable to change this default at this point, though.
