### ISSUE TITLE
Loaded TS resources will be loaded repeatedly

### ISSUE THREAD

**Issue by nikolamakin** [videojs/http-streaming#751]
Looking back at the content of the loaded TS resources, clicking on the scroll bar many times will load the TS resources repeatedly, but hls.js is not. How to solve it, thank you

### videojs version
video.js 7.6.6

### Browsers
google 80.0.3987.122 (64)

**Comment by gkatsev** [comment]
hls.js may be caching things itself I'm not sure. We rely on browser caching and it is recommended that appropriate caching headers are applied. If a mid-tier CDN shouldn't cache the segments, you should be able to do something like including `private` in the cache-control header rather than disallowing it altogether.
