### ISSUE TITLE
Safari choosing dash source instead of hls

### ISSUE THREAD

**Issue by tommhendrick** [videojs/http-streaming#905]
## Description
If I have a dash and hls source and try to play the video using safari it is trying to load the dash source instead of hls.

## Steps to reproduce
```
var src = [
            {
                src: video_url + 'video.mpd',
                type: 'application/dash+xml',
                withCredentials: true,
                keySystems: {
                    'com.widevine.alpha': 'https://drmurl.com',
                    'com.microsoft.playready': 'https://drmurl.com'
                }
            },
            {
                src: video_url + 'video.m3u8',
                type: 'application/x-mpegURL',
                withCredentials: true,
            }
        ];

        // Set the source to the player to init/start the playback.
        player.src(src);
```

### videojs version
video.js 7.8.3

### Browsers
Safari

### Platforms
Mac

**Comment by gkatsev** [comment]
This is because Video.js chooses the first playable source in the sources list. With this playback engine, we can play back DASH on Safari, so, we end up choosing it since it is listed first. Video.js doesn't currently take key systems into account when choosing whether a source can be played. Your best bet would be to not include the DASH source when playing back in Safari.
