### ISSUE TITLE
Cofused about initialization way

### ISSUE THREAD

**Issue by fancofang** [videojs/http-streaming#960]
## Description
Hi,
I follow README.md to initialization the plugin.
Your example is like that below doesn`t work.
```
// html5 for html hls
videojs(video, {
  html5: {
    vhs: {
      withCredentials: true
    }
  }
});
```

But if I change "vhs" to "hls"，then it works. Is it anything I get wrong?

**Comment by gkatsev** [comment]
The VHS option is the new way. Previously, we used `HLS` because we only supported HLS but now that this also supports DASH it was confusing. Going forward all options are going to be with `vhs`, though, `hls` will continue working.
Video.js doesn't include VHS 2.x yet (which is what is in the README and the main branch). When that gets into Video.js you can start using `vhs`.

**Comment by fancofang** [comment]
Thank you. I close the issue.
